### ISSUE TITLE
Failures when recording tests in saleor

### ISSUE THREAD

**Issue by apotterri** [applandinc/appmap-python#165]
As of https://github.com/saleor/saleor/commit/38df90a67 (i.e. when it was still using Django 3.2), most of the tests ran properly and generated AppMaps. 12 of them failed, however, because running with the agent attached caused extra SQL queries.

Details of the failures: 
[appmap-failures.log.zip](https://github.com/applandinc/appmap-python/files/9598024/appmap-failures.log.zip)

**Comment by symwell** [comment]
The zip with details of the failures contains
```
saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py:395:
E               Failed: Expected to perform 55 queries but 70 were done
```

I confirmed I see these failures too from `saleor/graphql/checkout/tests`
```
=========================================================================== short test summary info ============================================================================
FAILED saleor/graphql/checkout/tests/test_checkout_filters.py::test_checkout_query_with_filter_channels_with_one_channel - AssertionError: [{'message': 'More than one channe...
FAILED saleor/graphql/checkout/tests/test_checkout_filters.py::test_checkout_query_with_filter_channels_with_empty_channel - AssertionError: [{'message': 'More than one chan...
FAILED saleor/graphql/checkout/tests/test_checkout_filters.py::test_checkout_query_with_filter_channels_with_many_channel - AssertionError: [{'message': 'More than one chann...
FAILED saleor/graphql/checkout/tests/test_checkout_filters.py::test_checkout_query_with_filter_channels_without_channel - AssertionError: [{'message': 'More than one channel...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_add_checkout_lines - AssertionError: [{'message': 'super(): __class__ cell not found', 'locat...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_add_shipping_to_checkout - AssertionError: [{'message': 'super(): __class__ cell not found', ...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_create_checkout_with_reservations - AssertionError: [{'message': 'super(): __class__ cell not...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_add_delivery_to_checkout - AssertionError: [{'message': 'super(): __class__ cell not found', ...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_complete_checkout_with_out_of_stock_webhook - AssertionError: [{'message': 'super(): __class_...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_create_checkout - AssertionError: [{'message': 'super(): __class__ cell not found', 'location...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_update_checkout_lines_with_reservations - AssertionError: [{'message': 'super(): __class__ ce...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_add_billing_address_to_checkout - AssertionError: [{'message': 'super(): __class__ cell not f...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_update_checkout_lines - AssertionError: [{'message': 'super(): __class__ cell not found', 'lo...
FAILED saleor/graphql/checkout/tests/benchmark/test_homepage.py::test_user_checkout_details_with_tax_app - AssertionError: [{'message': 'super(): __class__ cell not found', ...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_checkout_payment_charge - AssertionError: [{'message': 'super(): __class__ cell not found', '...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_add_checkout_lines_with_reservations - AssertionError: [{'message': 'super(): __class__ cell ...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_add_checkout_lines_with_external_shipping - AssertionError: [{'message': 'super(): __class__ ...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_checkout_shipping_address_update - AssertionError: [{'message': 'super(): __class__ cell not ...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_complete_checkout - AssertionError: [{'message': 'super(): __class__ cell not found', 'locati...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_customer_complete_checkout - AssertionError: [{'message': 'super(): __class__ cell not found'...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_complete_checkout_with_single_line - AssertionError: [{'message': 'super(): __class__ cell no...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_checkout_email_update - AssertionError: [{'message': 'super(): __class__ cell not found', 'lo...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_checkout_voucher_code - AssertionError: [{'message': 'super(): __class__ cell not found', 'lo...
FAILED saleor/graphql/checkout/tests/benchmark/test_homepage.py::test_user_checkout_details - AssertionError: [{'message': 'super(): __class__ cell not found', 'locations': ...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_complete_checkout_with_digital_line - AssertionError: [{'message': 'super(): __class__ cell n...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_complete_checkout_preorder - AssertionError: [{'message': 'super(): __class__ cell not found'...
FAILED saleor/graphql/checkout/tests/benchmark/test_checkout_mutations.py::test_customer_complete_checkout_for_cc - AssertionError: [{'message': 'super(): __class__ cell not...
=========================================================== 27 failed, 563 passed, 31 warnings in 559.91s (0:09:19) ============================================================

```

**Comment by symwell** [comment]
With `APPMAP=true` `checkout_line.variant.preorder_global_threshold` is set to `None` instead of `7` after these lines

```
    variant = preorder_variant_channel_threshold
    variant.preorder_global_threshold = 7
    variant.save()
```

```
APPMAP=true py.test -s -v saleor/warehouse/tests/test_preorder_reservations_management.py

2022-10-17 10:39:09,632 WARNING saleor.warehouse.tests.test_preorder_reservations_management test_preorder_reservation_fails_if_global_threshold_was_allocated.2 has checkout_line.variant.preorder_global_threshold None [PID:5497:MainThread]
```

```
APPMAP=false py.test -s -v saleor/warehouse/tests/test_preorder_reservations_management.py

2022-10-17 10:36:06,921 WARNING saleor.warehouse.tests.test_preorder_reservations_management test_preorder_reservation_fails_if_global_threshold_was_allocated.2 has checkout_line.variant.preorder_global_threshold 7 [PID:5433:MainThread]
```

**Comment by symwell** [comment]
In another run:

Whatever happened between:
2022-10-17 10:52:43,685
and
2022-10-17 10:52:43,687
must be the bug

Basically these lines don't have the expected effect of `variant.preorder_global_threshold` being set to `7` 
```
    variant = preorder_variant_channel_threshold
    variant.preorder_global_threshold = 7
    variant.save()
```
```    
2022-10-17 10:52:43,685 WARNING saleor.warehouse.tests.test_preorder_reservations_management test_preorder_reservation_fails_if_global_threshold_was_allocated.0 will set variant.preorder_global_threshold [PID:5633:MainThread]
2022-10-17 10:52:43,687 WARNING saleor.warehouse.tests.test_preorder_reservations_management test_preorder_reservation_fails_if_global_threshold_was_allocated.1 has variant.preorder_global_threshold 7 [PID:5633:MainThread]
2022-10-17 10:52:43,687 WARNING saleor.warehouse.tests.test_preorder_reservations_management test_preorder_reservation_fails_if_global_threshold_was_allocated.2 has checkout_line.variant.preorder_global_threshold None [PID:5633:MainThread]
```

The queries at that time are:
```
2022-10-17 15:52:43.684 UTC [4477] LOG:  statement: UPDATE "checkout_checkoutline" SET "private_metadata" = '{}', "metadata" = '{}', "old_id" = NULL, "created_at" = '2022-10-17T15:52:43.675281+00:00'::timestamptz, "checkout_id" = '4343507d-504c-469e-82af-93f4d7d61575'::uuid, "variant_id" = 3, "quantity" = 5, "price_override" = NULL, "currency" = 'USD', "total_price_net_amount" = 0.000, "total_price_gross_amount" = 0.000, "tax_rate" = 0.0000 WHERE "checkout_checkoutline"."id" = '4d2c1c8f-ee52-4573-94ec-21b6f11cc05e'::uuid
2022-10-17 15:52:43.686 UTC [4477] LOG:  statement: UPDATE "product_productvariant" SET "sort_order" = 2, "private_metadata" = '{}', "metadata" = '{}', "sku" = 'SKU_B_P', "name" = '', "product_id" = 1, "track_inventory" = true, "is_preorder" = true, "preorder_end_date" = NULL, "preorder_global_threshold" = 7, "quantity_limit_per_customer" = NULL, "created_at" = '2022-10-17T15:52:43.642136+00:00'::timestamptz, "updated_at" = '2022-10-17T15:52:43.685929+00:00'::timestamptz, "weight" = NULL WHERE "product_productvariant"."id" = 3
2022-10-17 15:52:43.687 UTC [4477] LOG:  statement: INSERT INTO "product_productvariantchannellisting" ("variant_id", "channel_id", "currency", "price_amount", "cost_price_amount", "preorder_quantity_threshold") VALUES (3, 2, 'PLN', 10, 1, 10) RETURNING "product_productvariantchannellisting"."id"
```

These at the top and bottom look unusual

```
2022-10-17 15:52:43.619 UTC [4477] LOG:  statement: SAVEPOINT "s140019978090304_x8"
2022-10-17 15:52:43.620 UTC [4477] LOG:  statement: INSERT INTO "attribute_assignedvariantattribute" ("variant_id", "assignment_id") VALUES (1, 1) RETURNING "attribute_assignedvariantattribute"."id"
2022-10-17 15:52:43.621 UTC [4477] LOG:  statement: RELEASE SAVEPOINT "s140019978090304_x8"
```

```
2022-10-17 15:52:43.986 UTC [4477] LOG:  statement: SELECT 1
2022-10-17 15:52:43.986 UTC [4477] LOG:  statement: SET CONSTRAINTS ALL IMMEDIATE
2022-10-17 15:52:43.992 UTC [4477] LOG:  statement: SET CONSTRAINTS ALL DEFERRED
2022-10-17 15:52:43.992 UTC [4477] LOG:  statement: ROLLBACK
```

**Comment by symwell** [comment]
In summary, the correct SQL **does get issued** in response to these lines from `test_preorder_reservations_management.py:test_preorder_reservation_fails_if_global_threshold_was_allocated`

```
    variant = preorder_variant_channel_threshold
    variant.preorder_global_threshold = 7
    variant.save()
```

The SQL is
```
UPDATE "checkout_checkoutline"
   SET "private_metadata" = '{}',
       "metadata" = '{}',
       "old_id" = NULL,
       "created_at" = '2022-10-17T19:55:18.172088+00:00'::timestamptz,
       "checkout_id" = '55a36927-1934-4531-b2a9-17b066944eec'::uuid,
       "variant_id" = 3,
       "quantity" = 5,
       "price_override" = NULL,
       "currency" = 'USD',
       "total_price_net_amount" = 0.000,
       "total_price_gross_amount" = 0.000,
       "tax_rate" = 0.0000
WHERE "checkout_checkoutline"."id" = '56a9ed41-07bf-4298-88cd-450819a625e6'::uuid;

UPDATE "product_productvariant"
   SET "sort_order" = 2,
       "private_metadata" = '{}',
       "metadata" = '{}',
       "sku" = 'SKU_B_P',
       "name" = '',
       "product_id" = 1,
       "track_inventory" = true,
       "is_preorder" = true,
       "preorder_end_date" = NULL,
       "preorder_global_threshold" = 7,
       "quantity_limit_per_customer" = NULL,
       "created_at" = '2022-10-17T19:55:18.147799+00:00'::timestamptz,
       "updated_at" = '2022-10-17T19:55:18.186634+00:00'::timestamptz,
       "weight" = NULL
WHERE "product_productvariant"."id" = 3
```

This SQL intents to set `checkout_line.variant` to be `product_productvariant` with id 3. This would lead to `checkout_line.variant.preorder_global_threshold` to be `7`.

**But this update doesn't get applied.**  No exception is raised.

The table definition of `product_productvariant` reports:
```
\d product_productvariant

    TABLE "checkout_checkoutline" CONSTRAINT "cart_cartline_variant_id_dbca56c9_fk_product_productvariant_id" FOREIGN KEY (variant_id) REFERENCES product_productvariant(id) DEFERRABLE INITIALLY DEFERRED
```

This definition means it's ok to insert values that don't initially meet the referential integrity constraint as long as they do meet the constraint by the time the transaction ends.  Somehow the update doesn't get effected.

**Comment by symwell** [comment]
The test passed with
```
APPMAP_DISPLAY_PARAMS=false APPMAP=true py.test -s -v saleor/warehouse/tests/test_preorder_reservations_management.py
```

**Comment by symwell** [comment]
These fail
```
[gw2] FAILED saleor/graphql/app/tests/benchmarks/test_app_extensions.py::test_app_extensions_with_filter[filter2]
[gw3] FAILED saleor/graphql/account/tests/test_account_permission_group.py::test_permission_groups_query[permission_group_filter1-2]
[gw1] FAILED saleor/graphql/app/tests/benchmarks/test_app_extensions.py::test_app_extensions_with_filter[filter3]
[gw3] FAILED saleor/graphql/account/tests/test_pagination.py::test_query_customer_members_pagination_with_filter_search[customer_filter3-users_order3]
```
with the error message
```
Traceback (most recent call last):
  File "/app/saleor/channel/utils.py", line 27, in get_default_channel
    channel = Channel.objects.get()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
saleor.channel.models.Channel.DoesNotExist: Channel matching query does not exist.
```
The error means a query was issued to find a Channel object in the database but one did not exist.

**Comment by symwell** [comment]
fwiw with the recent release of appmap-python tests that used to fail now pass.  I'll run the full saleor testsuite again now.

**Comment by symwell** [comment]
Saleor contains 284K lines of code.  Must "the bug" be identified and fixed specifically in Saleor?  Is there no other free Python project with fewer lines of code that demonstrates this bug?

**Comment by apotterri** [comment]
Well, given that the bug is in the python agent, not in saleor, I'm not sure why the size of saleor is relevant. This also means that the fix wouldn't be specific to saleor.

**Comment by symwell** [comment]
Smaller code indicates higher code quality, including higher testcase quality.  I was expecting running the bad testcase would generate only a small number of queries but instead a lot of other things get executed before and after.  It's hard to isolate the effects of a single testcase.

**Comment by symwell** [comment]
The following Saleor testcase:
```
APPMAP_DISPLAY_PARAMS=false APPMAP=false pytest -s -v saleor/graphql/app/tests/benchmarks/test_app_extensions.py
```

fails when only the [function](https://github.com/saleor/saleor/blob/133b176a7983ef889dd60d2b80e0d556db269089/saleor/graphql/channel/utils.py#L14) `get_default_channel_slug_or_graphql_error` is instrumented.

**Comment by dividedmind** [comment]
> When only the [function](https://github.com/saleor/saleor/blob/133b176a7983ef889dd60d2b80e0d556db269089/saleor/graphql/channel/utils.py#L14) `get_default_channel_slug_or_graphql_error` is instrumented and nothing else is instrumented, the following Saleor testcase fails.
> 
> ```
> APPMAP_DISPLAY_PARAMS=false APPMAP=true pytest -s -v saleor/graphql/app/tests/benchmarks/test_app_extensions.py
> ```
> 
> The bug has to be related to instrumenting this function.
> 
> I'll try to reproduce this in a standalone testcase.

Thanks! #188 should fix this problem. I'm currently running the test suite with the fix to see if there's anything else.

**Comment by symwell** [comment]
With the fix from https://github.com/getappmap/appmap-python/pull/188 these pass:

> These fail
> 
> ```
> [gw2] FAILED saleor/graphql/app/tests/benchmarks/test_app_extensions.py::test_app_extensions_with_filter[filter2]
> [gw3] FAILED saleor/graphql/account/tests/test_account_permission_group.py::test_permission_groups_query[permission_group_filter1-2]
> [gw1] FAILED saleor/graphql/app/tests/benchmarks/test_app_extensions.py::test_app_extensions_with_filter[filter3]
> [gw3] FAILED saleor/graphql/account/tests/test_pagination.py::test_query_customer_members_pagination_with_filter_search[customer_filter3-users_order3]
> ```

**Comment by symwell** [comment]
All salor tests pass after the fix.

The tests that didn't pass when I ran all tests together do pass when run individually.
```
# these tests pass when I run them standalone
APPMAP_DISPLAY_PARAMS=false APPMAP=true pytest -s -v saleor/graphql/product/tests/test_product_type_update.py
APPMAP_DISPLAY_PARAMS=false APPMAP=true pytest -s -v saleor/graphql/product/tests/test_category.py
APPMAP_DISPLAY_PARAMS=false APPMAP=true pytest -s -v saleor/graphql/product/tests/test_product.py
APPMAP_DISPLAY_PARAMS=false APPMAP=true pytest -s -v saleor/graphql/product/tests/benchmark/test_product_variant_channel_listing_update.py
APPMAP_DISPLAY_PARAMS=false APPMAP=true pytest -s -v saleor/graphql/order/tests/deprecated/test_order.py; 
APPMAP_DISPLAY_PARAMS=false APPMAP=true pytest -s -v saleor/graphql/translations/tests/test_translations.py
APPMAP_DISPLAY_PARAMS=false APPMAP=true pytest -s -v saleor/graphql/product/tests/test_variant.py
```

6 out of 7 of the previous test failures were with a "Signature has expired" error. The load on my machine was high running the tests.  Maybe the failures were due to the high load.

I extracted saleor from commit 22fa83ecf3b20bec472c71fef0b4216e87bdbaa9 (Aug 26 2022) because the latest version couldn't start the docker containers for me.
